dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: test1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: ttc-campaigns-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.1.29
- name: ttc-connectors-dummytwitter
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.1.30
- name: ttc-rb-english-campaign
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.1.32
