dependencies:
- name: bp1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: test1
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: ttc-campaigns-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.1.32
- name: ttc-connectors-dummytwitter
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.1.34
- name: ttc-rb-english-campaign
  repository: http://jenkins-x-chartmuseum:8080
  version: 7.1.32
